### ISSUE TITLE
DiscordAPIError: Invalid Form Body embed.image.url: Not a well formed URL.

### ISSUE THREAD

**Issue by kitaminka** [Nimplex/ss-grabber.js#1]
![image](https://user-images.githubusercontent.com/54278668/95767998-512aa180-0cbe-11eb-95e9-4c71bc4e8c34.png)

**Comment by Nimplex** [comment]
I was too lazy to fix it, it only happens when the picture doesn't exist. i need to fix it

**Comment by Nimplex** [comment]
fixed
https://github.com/Nimplex/ss-grabber.js/commit/d50ecf0d1f24386c31187b2e75b6978f8afa79d3
